baseURL = 'https://teaching.wence.uk/comp4187/'
DefaultContentLanguage = 'en'
Language = 'en'
title = 'COMP4187 – Parallel Scientific Computing II'

staticDir = ['static']
disablePathToLower = false
enableGitInfo = true
enableRobotsTXT = false

theme = 'book'

disableKinds = ['taxonomy', 'taxonomyTerm']
# Needed for katex shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokailight'
    tabWidth = 8
    
[params]
BookSection = '/'
BookSearch = false
BookComments = false
BookToc = false
BookLogo = 'logo.svg'
BookRepo = 'https://github.com/wenceorg/comp4187'
ModulePage = 'https://www.dur.ac.uk/faculty.handbook/module_description/?year=2021&module_code=COMP4187'
BookEditPath = 'edit/master'
contentDir = 'site/content'
ImageDir = 'images'
CopyRight = '&copy; 2020-- [Lawrence Mitchell](mailto:lawrence@wence.uk), [Anne Reinarz](https://annereinarz.github.io) & [Durham University](https://www.dur.ac.uk/).'
